#!/bin/sh
### BEGIN INIT INFO
# Provides:          proxy
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the application.
### END INIT INFO
# kuangch create on 2017/04/21

project_name='web_frame_flask'

start(){
    chdir /var/$project_name
    nohup python main.pyc >/var/log/${project_name}.log & echo $!>/var/run/${project_name}.pid & 2>1 &
}


stop(){
   kill -9 $(cat /var/run/${project_name}.pid)
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: $prog {start|stop|restart|condrestart|try-restart|force-reload|upgrade|reload|status|help|configtest}"
        RETVAL=2
esac

exit $RETVAL
